//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Crests")]
	public partial class XpCrests : XPLiteObject
	{
		int fCrest_ID;
		[Key(true)]
		public int Crest_ID
		{
			get { return fCrest_ID; }
			set { SetPropertyValue<int>(nameof(Crest_ID), ref fCrest_ID, value); }
		}
		string fCity_Name;
		[Size(255)]
		public string City_Name
		{
			get { return fCity_Name; }
			set { SetPropertyValue<string>(nameof(City_Name), ref fCity_Name, value); }
		}
		byte[] fCrest_Image;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Crest_Image
		{
			get { return fCrest_Image; }
			set { SetPropertyValue<byte[]>(nameof(Crest_Image), ref fCrest_Image, value); }
		}
		[Association(@"XpCustomer_Store_LocationsReferencesXpCrests")]
		public XPCollection<XpCustomer_Store_Locations> Customer_Store_Locationss { get { return GetCollection<XpCustomer_Store_Locations>(nameof(Customer_Store_Locationss)); } }
	}

}
