//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Departments")]
	public partial class XpDepartments : XPLiteObject
	{
		int fDepartment_ID;
		[Key(true)]
		public int Department_ID
		{
			get { return fDepartment_ID; }
			set { SetPropertyValue<int>(nameof(Department_ID), ref fDepartment_ID, value); }
		}
		string fDepartment_Name;
		[Size(25)]
		public string Department_Name
		{
			get { return fDepartment_Name; }
			set { SetPropertyValue<string>(nameof(Department_Name), ref fDepartment_Name, value); }
		}
		[Association(@"XpEmployeesReferencesXpDepartments")]
		public XPCollection<XpEmployees> XpEmployeesCollection { get { return GetCollection<XpEmployees>(nameof(XpEmployeesCollection)); } }
	}

}
