//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Orders")]
	public partial class XpOrders : XPLiteObject
	{
		int fOrder_ID;
		[Key(true)]
		public int Order_ID
		{
			get { return fOrder_ID; }
			set { SetPropertyValue<int>(nameof(Order_ID), ref fOrder_ID, value); }
		}
		int? fOrder_Invoice_Number;
		[ColumnDbDefaultValue("((0))")]
		public int? Order_Invoice_Number
		{
			get { return fOrder_Invoice_Number; }
			set { SetPropertyValue<int?>(nameof(Order_Invoice_Number), ref fOrder_Invoice_Number, value); }
		}
		XpCustomers fOrder_Customer_ID;
		[Association(@"XpOrdersReferencesXpCustomers")]
		public XpCustomers Order_Customer_ID
		{
			get { return fOrder_Customer_ID; }
			set { SetPropertyValue<XpCustomers>(nameof(Order_Customer_ID), ref fOrder_Customer_ID, value); }
		}
		int? fOrder_Customer_Location_ID;
		[Indexed(Name = @"Orders$Order_Customer_Location_ID")]
		public int? Order_Customer_Location_ID
		{
			get { return fOrder_Customer_Location_ID; }
			set { SetPropertyValue<int?>(nameof(Order_Customer_Location_ID), ref fOrder_Customer_Location_ID, value); }
		}
		int? fOrder_PO_Number;
		[ColumnDbDefaultValue("((0))")]
		public int? Order_PO_Number
		{
			get { return fOrder_PO_Number; }
			set { SetPropertyValue<int?>(nameof(Order_PO_Number), ref fOrder_PO_Number, value); }
		}
		XpEmployees fOrder_Employee_ID;
		[Association(@"XpOrdersReferencesXpEmployees")]
		public XpEmployees Order_Employee_ID
		{
			get { return fOrder_Employee_ID; }
			set { SetPropertyValue<XpEmployees>(nameof(Order_Employee_ID), ref fOrder_Employee_ID, value); }
		}
		DateTime? fOrder_Date;
		public DateTime? Order_Date
		{
			get { return fOrder_Date; }
			set { SetPropertyValue<DateTime?>(nameof(Order_Date), ref fOrder_Date, value); }
		}
		decimal? fOrder_Sale_Amount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Sale_Amount
		{
			get { return fOrder_Sale_Amount; }
			set { SetPropertyValue<decimal?>(nameof(Order_Sale_Amount), ref fOrder_Sale_Amount, value); }
		}
		decimal? fOrder_Shipping_Amount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Shipping_Amount
		{
			get { return fOrder_Shipping_Amount; }
			set { SetPropertyValue<decimal?>(nameof(Order_Shipping_Amount), ref fOrder_Shipping_Amount, value); }
		}
		decimal? fOrder_Total_Amount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Total_Amount
		{
			get { return fOrder_Total_Amount; }
			set { SetPropertyValue<decimal?>(nameof(Order_Total_Amount), ref fOrder_Total_Amount, value); }
		}
		DateTime? fOrder_Ship_Date;
		public DateTime? Order_Ship_Date
		{
			get { return fOrder_Ship_Date; }
			set { SetPropertyValue<DateTime?>(nameof(Order_Ship_Date), ref fOrder_Ship_Date, value); }
		}
		string fOrder_Ship_Method;
		[Size(15)]
		public string Order_Ship_Method
		{
			get { return fOrder_Ship_Method; }
			set { SetPropertyValue<string>(nameof(Order_Ship_Method), ref fOrder_Ship_Method, value); }
		}
		string fOrder_Terms;
		[Size(15)]
		public string Order_Terms
		{
			get { return fOrder_Terms; }
			set { SetPropertyValue<string>(nameof(Order_Terms), ref fOrder_Terms, value); }
		}
		string fOrder_Comments;
		[Size(255)]
		public string Order_Comments
		{
			get { return fOrder_Comments; }
			set { SetPropertyValue<string>(nameof(Order_Comments), ref fOrder_Comments, value); }
		}
		[Association(@"XpOrder_ItemsReferencesXpOrders")]
		public XPCollection<XpOrder_Items> Order_Itemss { get { return GetCollection<XpOrder_Items>(nameof(Order_Itemss)); } }
	}

}
