//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Order_Items")]
	public partial class XpOrder_Items : XPLiteObject
	{
		int fOrder_Item_ID;
		[Key(true)]
		public int Order_Item_ID
		{
			get { return fOrder_Item_ID; }
			set { SetPropertyValue<int>(nameof(Order_Item_ID), ref fOrder_Item_ID, value); }
		}
		XpOrders fOrder_ID;
		[Association(@"XpOrder_ItemsReferencesXpOrders")]
		public XpOrders Order_ID
		{
			get { return fOrder_ID; }
			set { SetPropertyValue<XpOrders>(nameof(Order_ID), ref fOrder_ID, value); }
		}
		XpProducts fOrder_Item_Product_ID;
		[Association(@"XpOrder_ItemsReferencesXpProducts")]
		public XpProducts Order_Item_Product_ID
		{
			get { return fOrder_Item_Product_ID; }
			set { SetPropertyValue<XpProducts>(nameof(Order_Item_Product_ID), ref fOrder_Item_Product_ID, value); }
		}
		int? fOrder_Item_Product_Units;
		[ColumnDbDefaultValue("((0))")]
		public int? Order_Item_Product_Units
		{
			get { return fOrder_Item_Product_Units; }
			set { SetPropertyValue<int?>(nameof(Order_Item_Product_Units), ref fOrder_Item_Product_Units, value); }
		}
		decimal? fOrder_Item_Product_Price;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Item_Product_Price
		{
			get { return fOrder_Item_Product_Price; }
			set { SetPropertyValue<decimal?>(nameof(Order_Item_Product_Price), ref fOrder_Item_Product_Price, value); }
		}
		decimal? fOrder_Item_Discount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Item_Discount
		{
			get { return fOrder_Item_Discount; }
			set { SetPropertyValue<decimal?>(nameof(Order_Item_Discount), ref fOrder_Item_Discount, value); }
		}
		decimal? fOrder_Item_Total;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Item_Total
		{
			get { return fOrder_Item_Total; }
			set { SetPropertyValue<decimal?>(nameof(Order_Item_Total), ref fOrder_Item_Total, value); }
		}
	}

}
