//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Product_Images")]
	public partial class XpProduct_Images : XPLiteObject
	{
		int fImage_ID;
		[Key(true)]
		public int Image_ID
		{
			get { return fImage_ID; }
			set { SetPropertyValue<int>(nameof(Image_ID), ref fImage_ID, value); }
		}
		XpProducts fProduct_ID;
		[Association(@"XpProduct_ImagesReferencesXpProducts")]
		public XpProducts Product_ID
		{
			get { return fProduct_ID; }
			set { SetPropertyValue<XpProducts>(nameof(Product_ID), ref fProduct_ID, value); }
		}
		byte[] fProduct_Image;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Product_Image
		{
			get { return fProduct_Image; }
			set { SetPropertyValue<byte[]>(nameof(Product_Image), ref fProduct_Image, value); }
		}
	}

}
