//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.XPO.DevAV
{

	[Persistent(@"Quotes")]
	public partial class XpQuotes : XPLiteObject
	{
		int fQuote_ID;
		[Key(true)]
		public int Quote_ID
		{
			get { return fQuote_ID; }
			set { SetPropertyValue<int>(nameof(Quote_ID), ref fQuote_ID, value); }
		}
		int? fQuote_Number;
		[ColumnDbDefaultValue("((0))")]
		public int? Quote_Number
		{
			get { return fQuote_Number; }
			set { SetPropertyValue<int?>(nameof(Quote_Number), ref fQuote_Number, value); }
		}
		XpCustomers fQuote_Customer_ID;
		[Association(@"XpQuotesReferencesXpCustomers")]
		public XpCustomers Quote_Customer_ID
		{
			get { return fQuote_Customer_ID; }
			set { SetPropertyValue<XpCustomers>(nameof(Quote_Customer_ID), ref fQuote_Customer_ID, value); }
		}
		int? fQuote_Customer_Location_ID;
		[Indexed(Name = @"Quotes$Order_Customer_Location_ID")]
		public int? Quote_Customer_Location_ID
		{
			get { return fQuote_Customer_Location_ID; }
			set { SetPropertyValue<int?>(nameof(Quote_Customer_Location_ID), ref fQuote_Customer_Location_ID, value); }
		}
		XpEmployees fQuote_Employee_ID;
		[Association(@"XpQuotesReferencesXpEmployees")]
		public XpEmployees Quote_Employee_ID
		{
			get { return fQuote_Employee_ID; }
			set { SetPropertyValue<XpEmployees>(nameof(Quote_Employee_ID), ref fQuote_Employee_ID, value); }
		}
		DateTime? fQuote_Date;
		public DateTime? Quote_Date
		{
			get { return fQuote_Date; }
			set { SetPropertyValue<DateTime?>(nameof(Quote_Date), ref fQuote_Date, value); }
		}
		decimal? fQuote_SubTotal;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Quote_SubTotal
		{
			get { return fQuote_SubTotal; }
			set { SetPropertyValue<decimal?>(nameof(Quote_SubTotal), ref fQuote_SubTotal, value); }
		}
		decimal? fQuote_Shipping_Amount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Quote_Shipping_Amount
		{
			get { return fQuote_Shipping_Amount; }
			set { SetPropertyValue<decimal?>(nameof(Quote_Shipping_Amount), ref fQuote_Shipping_Amount, value); }
		}
		decimal? fOrder_Total;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Order_Total
		{
			get { return fOrder_Total; }
			set { SetPropertyValue<decimal?>(nameof(Order_Total), ref fOrder_Total, value); }
		}
		decimal? fQuote_Total;
		public decimal? Quote_Total
		{
			get { return fQuote_Total; }
			set { SetPropertyValue<decimal?>(nameof(Quote_Total), ref fQuote_Total, value); }
		}
		double? fQuote_Opportunity;
		public double? Quote_Opportunity
		{
			get { return fQuote_Opportunity; }
			set { SetPropertyValue<double?>(nameof(Quote_Opportunity), ref fQuote_Opportunity, value); }
		}
		[Association(@"XpQuote_ItemsReferencesXpQuotes")]
		public XPCollection<XpQuote_Items> Quote_Itemss { get { return GetCollection<XpQuote_Items>(nameof(Quote_Itemss)); } }
	}

}
