//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.DevAV
{

	[Persistent(@"Customer_Store_Locations")]
	public partial class XpCustomer_Store_Locations : XPLiteObject
	{
		int fCustomer_Store_ID;
		[Key(true)]
		public int Customer_Store_ID
		{
			get { return fCustomer_Store_ID; }
			set { SetPropertyValue<int>(nameof(Customer_Store_ID), ref fCustomer_Store_ID, value); }
		}
		XpCustomers fCustomer_ID;
		[Association(@"XpCustomer_Store_LocationsReferencesXpCustomers")]
		public XpCustomers Customer_ID
		{
			get { return fCustomer_ID; }
			set { SetPropertyValue<XpCustomers>(nameof(Customer_ID), ref fCustomer_ID, value); }
		}
		string fCustomer_Store_Location;
		[Size(255)]
		public string Customer_Store_Location
		{
			get { return fCustomer_Store_Location; }
			set { SetPropertyValue<string>(nameof(Customer_Store_Location), ref fCustomer_Store_Location, value); }
		}
		string fCustomer_Store_Address;
		[Size(255)]
		public string Customer_Store_Address
		{
			get { return fCustomer_Store_Address; }
			set { SetPropertyValue<string>(nameof(Customer_Store_Address), ref fCustomer_Store_Address, value); }
		}
		string fCustomer_Store_City;
		[Size(255)]
		public string Customer_Store_City
		{
			get { return fCustomer_Store_City; }
			set { SetPropertyValue<string>(nameof(Customer_Store_City), ref fCustomer_Store_City, value); }
		}
		int? fCustomer_Store_State;
		public int? Customer_Store_State
		{
			get { return fCustomer_Store_State; }
			set { SetPropertyValue<int?>(nameof(Customer_Store_State), ref fCustomer_Store_State, value); }
		}
		int? fCustomer_Store_Zipcode;
		[Indexed(Name = @"Customer_Store_Locations$Customer_Store_Zipcode")]
		[ColumnDbDefaultValue("((0))")]
		public int? Customer_Store_Zipcode
		{
			get { return fCustomer_Store_Zipcode; }
			set { SetPropertyValue<int?>(nameof(Customer_Store_Zipcode), ref fCustomer_Store_Zipcode, value); }
		}
		string fCustomer_Store_Phone;
		[Size(255)]
		public string Customer_Store_Phone
		{
			get { return fCustomer_Store_Phone; }
			set { SetPropertyValue<string>(nameof(Customer_Store_Phone), ref fCustomer_Store_Phone, value); }
		}
		string fCustomer_Store_Fax;
		[Size(255)]
		public string Customer_Store_Fax
		{
			get { return fCustomer_Store_Fax; }
			set { SetPropertyValue<string>(nameof(Customer_Store_Fax), ref fCustomer_Store_Fax, value); }
		}
		int? fCustomer_Store_Total_Employees;
		[ColumnDbDefaultValue("((0))")]
		public int? Customer_Store_Total_Employees
		{
			get { return fCustomer_Store_Total_Employees; }
			set { SetPropertyValue<int?>(nameof(Customer_Store_Total_Employees), ref fCustomer_Store_Total_Employees, value); }
		}
		int? fCustomer_Store_Square_Footage;
		[ColumnDbDefaultValue("((0))")]
		public int? Customer_Store_Square_Footage
		{
			get { return fCustomer_Store_Square_Footage; }
			set { SetPropertyValue<int?>(nameof(Customer_Store_Square_Footage), ref fCustomer_Store_Square_Footage, value); }
		}
		decimal? fCustomer_Store_Annual_Sales;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Customer_Store_Annual_Sales
		{
			get { return fCustomer_Store_Annual_Sales; }
			set { SetPropertyValue<decimal?>(nameof(Customer_Store_Annual_Sales), ref fCustomer_Store_Annual_Sales, value); }
		}
		XpCrests fCrest_ID;
		[Association(@"XpCustomer_Store_LocationsReferencesXpCrests")]
		public XpCrests Crest_ID
		{
			get { return fCrest_ID; }
			set { SetPropertyValue<XpCrests>(nameof(Crest_ID), ref fCrest_ID, value); }
		}
		[Association(@"XpCustomer_EmployeesReferencesXpCustomer_Store_Locations")]
		public XPCollection<XpCustomer_Employees> Customer_Employeess { get { return GetCollection<XpCustomer_Employees>(nameof(Customer_Employeess)); } }
	}

}
