//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.DevAV
{

	[Persistent(@"Customer_Employees")]
	public partial class XpCustomer_Employees : XPLiteObject
	{
		int fCustomer_Employee_ID;
		[Key(true)]
		public int Customer_Employee_ID
		{
			get { return fCustomer_Employee_ID; }
			set { SetPropertyValue<int>(nameof(Customer_Employee_ID), ref fCustomer_Employee_ID, value); }
		}
		XpCustomers fCustomer_ID;
		[Association(@"XpCustomer_EmployeesReferencesXpCustomers")]
		public XpCustomers Customer_ID
		{
			get { return fCustomer_ID; }
			set { SetPropertyValue<XpCustomers>(nameof(Customer_ID), ref fCustomer_ID, value); }
		}
		XpCustomer_Store_Locations fCustomer_Store_ID;
		[Association(@"XpCustomer_EmployeesReferencesXpCustomer_Store_Locations")]
		public XpCustomer_Store_Locations Customer_Store_ID
		{
			get { return fCustomer_Store_ID; }
			set { SetPropertyValue<XpCustomer_Store_Locations>(nameof(Customer_Store_ID), ref fCustomer_Store_ID, value); }
		}
		string fCustomer_Employee_First_Name;
		[Size(255)]
		public string Customer_Employee_First_Name
		{
			get { return fCustomer_Employee_First_Name; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_First_Name), ref fCustomer_Employee_First_Name, value); }
		}
		string fCustomer_Employee_Last_Name;
		[Size(255)]
		public string Customer_Employee_Last_Name
		{
			get { return fCustomer_Employee_Last_Name; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Last_Name), ref fCustomer_Employee_Last_Name, value); }
		}
		string fCustomer_Employee_Full_Name;
		[Size(255)]
		public string Customer_Employee_Full_Name
		{
			get { return fCustomer_Employee_Full_Name; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Full_Name), ref fCustomer_Employee_Full_Name, value); }
		}
		string fCustomer_Employee_Prefix;
		[Indexed(Name = @"Customer_Employees$Zipcode")]
		[Size(15)]
		public string Customer_Employee_Prefix
		{
			get { return fCustomer_Employee_Prefix; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Prefix), ref fCustomer_Employee_Prefix, value); }
		}
		string fCustomer_Employee_Position;
		[Size(25)]
		public string Customer_Employee_Position
		{
			get { return fCustomer_Employee_Position; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Position), ref fCustomer_Employee_Position, value); }
		}
		string fCustomer_Employee_Mobile_Phone;
		[Size(255)]
		public string Customer_Employee_Mobile_Phone
		{
			get { return fCustomer_Employee_Mobile_Phone; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Mobile_Phone), ref fCustomer_Employee_Mobile_Phone, value); }
		}
		string fCustomer_Employee_Email;
		public string Customer_Employee_Email
		{
			get { return fCustomer_Employee_Email; }
			set { SetPropertyValue<string>(nameof(Customer_Employee_Email), ref fCustomer_Employee_Email, value); }
		}
		bool? fCustomer_Purchase_Authority;
		[ColumnDbDefaultValue("((0))")]
		public bool? Customer_Purchase_Authority
		{
			get { return fCustomer_Purchase_Authority; }
			set { SetPropertyValue<bool?>(nameof(Customer_Purchase_Authority), ref fCustomer_Purchase_Authority, value); }
		}
		byte[] fCustomer_Employee_Picture;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Customer_Employee_Picture
		{
			get { return fCustomer_Employee_Picture; }
			set { SetPropertyValue<byte[]>(nameof(Customer_Employee_Picture), ref fCustomer_Employee_Picture, value); }
		}
		[Association(@"XpCustomer_CommunicationsReferencesXpCustomer_Employees")]
		public XPCollection<XpCustomer_Communications> Customer_Communicationss { get { return GetCollection<XpCustomer_Communications>(nameof(Customer_Communicationss)); } }
		[Association(@"XpTasksReferencesXpCustomer_Employees")]
		public XPCollection<XpTasks> XpTasksCollection { get { return GetCollection<XpTasks>(nameof(XpTasksCollection)); } }
	}

}
