//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.DevAV
{

	[Persistent(@"Evaluations")]
	public partial class XpEvaluations : XPLiteObject
	{
		int fNote_ID;
		[Key(true)]
		public int Note_ID
		{
			get { return fNote_ID; }
			set { SetPropertyValue<int>(nameof(Note_ID), ref fNote_ID, value); }
		}
		XpEmployees fCreated_By_ID;
		[Association(@"XpEvaluationsReferencesXpEmployees")]
		public XpEmployees Created_By_ID
		{
			get { return fCreated_By_ID; }
			set { SetPropertyValue<XpEmployees>(nameof(Created_By_ID), ref fCreated_By_ID, value); }
		}
		DateTime? fCreated_On;
		public DateTime? Created_On
		{
			get { return fCreated_On; }
			set { SetPropertyValue<DateTime?>(nameof(Created_On), ref fCreated_On, value); }
		}
		XpEmployees fEmployee_ID;
		[Association(@"XpEvaluationsReferencesXpEmployees1")]
		public XpEmployees Employee_ID
		{
			get { return fEmployee_ID; }
			set { SetPropertyValue<XpEmployees>(nameof(Employee_ID), ref fEmployee_ID, value); }
		}
		string fSubject;
		[Size(255)]
		public string Subject
		{
			get { return fSubject; }
			set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
		}
		string fDetails;
		[Size(SizeAttribute.Unlimited)]
		public string Details
		{
			get { return fDetails; }
			set { SetPropertyValue<string>(nameof(Details), ref fDetails, value); }
		}
	}

}
