//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.DevAV
{

	[Persistent(@"Quote_Items")]
	public partial class XpQuote_Items : XPLiteObject
	{
		int fQuote_Item_ID;
		[Key(true)]
		public int Quote_Item_ID
		{
			get { return fQuote_Item_ID; }
			set { SetPropertyValue<int>(nameof(Quote_Item_ID), ref fQuote_Item_ID, value); }
		}
		XpQuotes fQuote_ID;
		[Association(@"XpQuote_ItemsReferencesXpQuotes")]
		public XpQuotes Quote_ID
		{
			get { return fQuote_ID; }
			set { SetPropertyValue<XpQuotes>(nameof(Quote_ID), ref fQuote_ID, value); }
		}
		XpProducts fQuote_Item_Product_ID;
		[Association(@"XpQuote_ItemsReferencesXpProducts")]
		public XpProducts Quote_Item_Product_ID
		{
			get { return fQuote_Item_Product_ID; }
			set { SetPropertyValue<XpProducts>(nameof(Quote_Item_Product_ID), ref fQuote_Item_Product_ID, value); }
		}
		int? fQuote_Item_Product_Units;
		[ColumnDbDefaultValue("((0))")]
		public int? Quote_Item_Product_Units
		{
			get { return fQuote_Item_Product_Units; }
			set { SetPropertyValue<int?>(nameof(Quote_Item_Product_Units), ref fQuote_Item_Product_Units, value); }
		}
		decimal? fQuote_Item_Product_Price;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Quote_Item_Product_Price
		{
			get { return fQuote_Item_Product_Price; }
			set { SetPropertyValue<decimal?>(nameof(Quote_Item_Product_Price), ref fQuote_Item_Product_Price, value); }
		}
		decimal? fQuote_Item_Discount;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Quote_Item_Discount
		{
			get { return fQuote_Item_Discount; }
			set { SetPropertyValue<decimal?>(nameof(Quote_Item_Discount), ref fQuote_Item_Discount, value); }
		}
		decimal? fQuote_Item_Total;
		[ColumnDbDefaultValue("((0))")]
		public decimal? Quote_Item_Total
		{
			get { return fQuote_Item_Total; }
			set { SetPropertyValue<decimal?>(nameof(Quote_Item_Total), ref fQuote_Item_Total, value); }
		}
	}

}
