//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevAVXPO.Models.DevAV
{

	[Persistent(@"States")]
	public partial class XpStates : XPLiteObject
	{
		int fSate_ID;
		[Key(true)]
		public int Sate_ID
		{
			get { return fSate_ID; }
			set { SetPropertyValue<int>(nameof(Sate_ID), ref fSate_ID, value); }
		}
		string fState_Short;
		[Size(2)]
		public string State_Short
		{
			get { return fState_Short; }
			set { SetPropertyValue<string>(nameof(State_Short), ref fState_Short, value); }
		}
		string fState_Long;
		[Size(255)]
		public string State_Long
		{
			get { return fState_Long; }
			set { SetPropertyValue<string>(nameof(State_Long), ref fState_Long, value); }
		}
		byte[] fFlag_48px;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Flag_48px
		{
			get { return fFlag_48px; }
			set { SetPropertyValue<byte[]>(nameof(Flag_48px), ref fFlag_48px, value); }
		}
		byte[] fFlag_24px;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Flag_24px
		{
			get { return fFlag_24px; }
			set { SetPropertyValue<byte[]>(nameof(Flag_24px), ref fFlag_24px, value); }
		}
		[Association(@"XpCustomersReferencesXpStates")]
		public XPCollection<XpCustomers> XpCustomersCollection { get { return GetCollection<XpCustomers>(nameof(XpCustomersCollection)); } }
		[Association(@"XpEmployeesReferencesXpStates")]
		public XPCollection<XpEmployees> XpEmployeesCollection { get { return GetCollection<XpEmployees>(nameof(XpEmployeesCollection)); } }
	}

}
